// Generated by CoffeeScript 1.3.3
var app, assets, db, express, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

db = require('./cfg-mongoose');

app = express();

app.configure(function() {
  return app.use(express.bodyParser());
});

app.configure('development', function() {
  console.log("* development mode");
  app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
  return db.startup('mongodb://localhost/dravvo', true);
});

app.configure('production', function() {
  var dburl, env, mongo;
  console.log("* production mode");
  app.use(express.errorHandler());
  if (!(process.env.VCAP_SERVICES != null)) {
    console.log("Error: couldnt find VCAP_SERVICES in process.env");
  }
  env = JSON.parse(process.env.VCAP_SERVICES);
  mongo = env['mongodb-1.8'][0]['credentials'];
  dburl = "mongodb://" + mongo.username + ":" + mongo.password + "@" + mongo.hostname + ":" + mongo.port + "/" + mongo.db;
  return db.startup(dburl);
});

require('../routes')(app);

port = process.env.VCAP_APP_PORT || process.env.PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
