// Generated by CoffeeScript 1.3.3
var app, assets, db, express, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

db = require('./cfg-mongoose');

app = express();

app.configure(function() {
  app.set('view engine', 'jade');
  return app.use(express.bodyParser());
});

app.configure('development', function() {
  console.log("* development mode");
  app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
  db.startup('mongodb://localhost/dravvo');
  return db.seedTextMessages(true);
});

app.configure('production', function() {
  console.log("* production mode");
  app.use(express.errorHandler());
  return db.startup('mongodb://localhost/expdb');
});

require('../routes')(app);

port = process.env.VCAP_APP_PORT || process.env.PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
