// Generated by CoffeeScript 1.3.3
var mongoose;

mongoose = require('mongoose');

module.exports = {
  startup: function(dbURL, withSeeds) {
    var _this = this;
    if (withSeeds == null) {
      withSeeds = false;
    }
    console.log("Waiting for MongoDB connection...");
    mongoose.connect(dbURL);
    return mongoose.connection.on('open', function() {
      return console.log('...connected');
    });
  },
  close: function() {
    return mongoose.disconnect();
  }
};
